### ISSUE TITLE
Populate the classes list page

### ISSUE THREAD

**Issue by hex337** [hex337/quantum-attendance#5]
Pull existing classes for the list page, with pagination.

**Comment by hex337** [comment]
We can pull the classes now, but not with pagination.

**Comment by hex337** [comment]
Ok, so for this, you'll need to modify the `client/app/bundles/Attendance/components/ClassesScreen/ClassesList/ClassesList.jsx` class. Currently,  in the production app, we display the Class Type, the Met date and time, number of students who were in class, and the comment field.

The current data model stores a class type id with each class, you'll have to update the json that we return to pull in the class type, which you would do in `app/controllers/meetings_controller.rb` in the index function. Right now, we are just pulling the meeting objects and running `.to_json` on them. If you look in `app/controllers/members_controller.rb` in the index function, you'll see an example of how to pull another model into the current one before you serialize to json. You'll also want to read up on the [includes](http://blog.arkency.com/2013/12/rails4-preloading/) function in rails.

You'll be updating the data model of what we store in the redux store, which means that we want to update the `PropTypes` to ensure we're getting the right models. Take a look at [ClassesList.jsx line 6]() where I define the `PropTypes` for a class. This will need to get expanded. I would create a new component, called `ClassType` in `components` and then in `components/ClassType/ClassType.jsx` export a const that validates a class type object.

I think that as a start will be enough, once you get through this, we can take a look at how to pull in the student count information.

**Comment by mlamina** [comment]
Thanks for all the pointers! I'll dig into it today :)

**Comment by hex337** [comment]
Here's a great [blog post](https://medium.freecodecamp.org/all-the-fundamental-react-js-concepts-jammed-into-this-single-medium-article-c83f9b53eac2) with the basics of React.
